### PR TITLE
Port to gtk3

### PR DESCRIPTION
**Pull request by leigh123linux**
Looking at the roadmap

> mate 1.16
>     swith MATE to GTK3
>     switch mintmenu to GTK3

This pull will require a few tweaks and testing as I've only tested with gtk-3.21.5

### CODE REVIEW

**Comment by clefebvre** [comment]
Quick note on this.

We're shipping MATE 1.16 in GTK2 in Linux Mint 18.1. 

Hopefully we can move to GTK3 with MATE 1.18 and Mint 18.2.

**Comment by monsta** [comment]
Can you please fix the conflicts? I'm running GTK+3 build of MATE here in my Mint 18 and would like to test this.

**Comment by leigh123linux** [comment]
@monsta Give it a go now

**Comment by monsta** [comment]
Thanks, works alright in my Mint 18 with a couple of issues:

- right-click menu never shows up - in applications, favorites and trash
- when menu is opened, "Menu" text on the button becomes white (tested with Mint-X and some of mate-themes)

Both issues are also present in mate-menu fork. However, right-click works in Ubuntu 16.10 (GTK+ 3.20.9) and Debian Testing (GTK+ 3.22.4). Here in Mint 18 we have GTK+ 3.18.9.

**Comment by monsta** [comment]
The only error message I got is when I try to open right-click menu in applications pane:

```
Nov 29 21:53:06 asylum org.mate.panel.applet.MintMenuAppletFactory[11912]: Traceback (most recent call last):
Nov 29 21:53:06 asylum org.mate.panel.applet.MintMenuAppletFactory[11912]:   File "/usr/lib/linuxmint/mintMenu/plugins/applications.py", line 1007, in menuPopup
Nov 29 21:53:06 asylum org.mate.panel.applet.MintMenuAppletFactory[11912]:     mTree.popup(None, None, None, None, ev.button, ev.time)
Nov 29 21:53:06 asylum org.mate.panel.applet.MintMenuAppletFactory[11912]: NameError: global name 'ev' is not defined
```
Right-click menu in favorites pane and on trash item in places fails silently.

**Comment by monsta** [comment]
I stumbled upon https://github.com/linuxmint/mintmenu/issues/133 and realized that one more mate-menu issue (mentioned there) is also present here: reordering favorites via drag-n-drop doesn't work. You can drag an item around, but dropping it anywhere does nothing.

**Comment by monsta** [comment]
@clefebvre: forgot to tell you that it also needs fixing for GTK+ 3.14...

```
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: Traceback (most recent call last):
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: File "/usr/lib/mate-menu/mate-menu.py", line 746, in showMenu
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: self.toggleMenu()
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: File "/usr/lib/mate-menu/mate-menu.py", line 758, in toggleMenu
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: self.positionMenu()
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: File "/usr/lib/mate-menu/mate-menu.py", line 771, in positionMenu
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: entryX = self.applet.get_window().get_origin().x
мар 19 11:07:46 betsy org.mate.panel.applet.MateMenuAppletFactory[1117]: AttributeError: 'tuple' object has no attribute '
```

Just in case you'd want to ship MATE 1.18 (which is GTK+3) in LMDE 2 :slightly_smiling_face:

**Comment by clefebvre** [comment]
@monsta I'll merge this for now and continue to fix it on master. Moving to GTK3 will require breaking from the past anyway, so we'll have to branch out if we need maintenance.

**Comment by monsta** [comment]
Fine with me, I'm already glad it's merged, it opens a path for PRs :slightly_smiling_face: 
I've seen some fixes at https://bitbucket.org/ubuntu-mate/mate-menu/commits/all

**Comment by clefebvre** [comment]
ok, all fixed now afaik.

**Comment by monsta** [comment]
Cool, thanks :slightly_smiling_face:

**Comment by monsta** [comment]
I only have this one remaining:

> when menu is opened, "Menu" text on the button becomes white (tested with Mint-X and some of mate-themes)

**Comment by JosephMcc** [comment]
@monsta quite possibly just a theming issue. Going to start digging into porting our stuff for gtk3 Mate now that I have it installed.

**Pull request merged**
